### PR TITLE
Integrate IPFS

### PR DESCRIPTION
**Pull request by arobsn**
This PR replaces imgbb for IPFS as an artwork storage via the following changes:

- added `ipfs-core` as a package dependence
- changed `uploadArtwork()` function at src/utils/issueArtwork.js to add file to IPFS and return gateway url

### Comment
I'm not sure this is what you expected in #1, but if you need any further work on this, please let me know.

### CODE REVIEW

**Comment by anon-real** [comment]
@anon-br just tested. I don't think that works. The artwork (picture, audio) must be uploaded into IPFS and a direct link be returned by the method but it doesn't seem to happen here as the link does not work.

**Comment by arobsn** [comment]
Well, it should happen. I've tested and it worked well, will check this today later.

**Comment by bdkent** [comment]
I think your going to have to [pin](https://docs.ipfs.io/how-to/pin-files/#pin-files-using-ipfs) the file somewhere.

As far as I know cloudfare [doesn't pin](https://community.cloudflare.com/t/do-you-pin-ipfs-files/40354).  You'll need a [pin service](https://docs.ipfs.io/concepts/persistence/#pinning-services) or to run a node [as part of the server](https://docs.ipfs.io/how-to/run-ipfs-inside-docker/#run-ipfs-inside-docker) with dedicated storage and pin there.

You should probably also return a more generic URI (ie, `ipfs://${cid}`) so you aren't tied to cloudflare.

**Comment by anon-real** [comment]
@anon-br after a while, the uploaded file appeared. But I am afraid @bdkent is right, please investigate to make sure the approach is permanent and always works.

**Comment by catalyst244** [comment]
We fixed this issue because we need to pass host and port address for right uploading process so the broken url is already fixed
@anon-real

**Comment by catalyst244** [comment]
So we defined "https://ipfs.infura.io:5001" as host and problem solved!!

**Comment by arobsn** [comment]
> @anon-br after a while, the uploaded file appeared. But I am afraid @bdkent is right, please investigate to make sure the approach is permanent and always works.

Ok, will check this. I think @bdkent is right about pinning it, sorry for forgetting about this. I'm accompanying my wife to the hospital for routine checkups and as soon as I can put my hands on a keyboard, I check this ;)

**Comment by bdkent** [comment]
@anon-real It might be interesting to generalize this a bit more for broader Ergo + IPFS usage. You could have a service running that has per-smart-contact plugins to scan boxes/etc for known IPFS hash locations and then pins them for permanent storage.

**Comment by arobsn** [comment]
> You should probably also return a more generic URI (ie, `ipfs://${cid}`) so you aren't tied to cloudflare.

@bdkent ideally, it should be like that. But the issue #1 requires a solution "in a way that the auction house doesn't break" and, since most browsers don't natively support `ipsf://`, it will break. If @anon-real agrees, I can return a URI like you described and open a PR in the auction house to handle it by using a gateway like cloudflare or infura.

**Comment by arobsn** [comment]
@anon-br is a paid pining service like [Pinata](https://www.pinata.cloud/) or [infura](https://infura.io/product/ipfs) an option?

**Comment by anon-real** [comment]
> > You should probably also return a more generic URI (ie, `ipfs://${cid}`) so you aren't tied to cloudflare.
> 
> @bdkent ideally, it should be like that. But the issue #1 requires a solution "in a way that the auction house doesn't break" and, since most browsers don't natively support `ipsf://`, it will break. If @anon-real agrees, I can return a URI like you described and open a PR in the auction house to handle it by using a gateway like cloudflare or infura.

This also can work!

**Comment by anon-real** [comment]
> @anon-br is a paid pining service like [Pinata](https://www.pinata.cloud/) or [infura](https://infura.io/product/ipfs) an option?

What are the options?

**Comment by arobsn** [comment]
@anon-real as far as I know there aren't many options, I've tried [nft.storage](https://nft.storage/) that uses IPFS + Filecoin as a free option, but the service stills in beta and its API implementation seems pretty buggy.

Another option is to request API keys from users of services like pinata, as these have free plains that looks good enough for individual users. But I'm not sure if is this is an option here, once this doesn't seems to be so user friendly and requires an account on a third part service.

**Comment by anon-real** [comment]
@anon-br @bdkent  So what are your suggestions? I think we need this sooner than later.

**Comment by arobsn** [comment]
@anon-real I like the second approach and I think it's more sustainable while keeping the responsibility of keeping the files available with the user, but it can add some UX complexity to the minting process.

**Comment by arobsn** [comment]
### New commit
 - removed `ipfs-core` as a dependence
 - added nft.storage as an upload and pinning IPFS service on `uploadArtwork()`
 - changed `uploadArtwork()` to return IPFS protocol URI
 - added some ui changes on `\src\UtilPage\TokenUtils\General\pictureNFT.js` to reflect these changes


### Comment

> I've tried [nft.storage](https://nft.storage/) that uses IPFS + Filecoin as a free option, but the service stills in beta and its API implementation seems pretty buggy.

Well actually my browser was buggy, not the service. After realizing this, I switched off some extensions and it worked like a charm! Sorry about that, guys.

**Comment by bdkent** [comment]
> ### New commit
> 
>     * removed `ipfs-core` as a dependence
> 
>     * added nft.storage as an upload and pinning IPFS service on `uploadArtwork()`
> 
>     * changed `uploadArtwork()` to return IPFS protocol URI
> 
>     * added some ui changes on `\src\UtilPage\TokenUtils\General\pictureNFT.js` to reflect these changes
> 
> 
> ### Comment
> 
> > I've tried [nft.storage](https://nft.storage/) that uses IPFS + Filecoin as a free option, but the service stills in beta and its API implementation seems pretty buggy.
> 
> Well actually my browser was buggy, not the service. After realizing this, I switched off some extensions and it worked like a charm! Sorry about that, guys.

nft.storage seems like a good service! And will ostensibly remain free for NFTs (unlike a lot of these IPFS pinning services that are free for a while and then start charging).  While the current client-side solution works, it does expose the API key which seems like it opens the service up to nefarious attackers.  Couldn't someone take the API key and then [delete](https://ipfs-shipyard.github.io/nft.storage/client/classes/NFTStorage.html#delete) the CID (allowing it to fall out of IPFS eventually)?  It seems like you might need a backend service that holds the API key and actually interacts with nft.storage.

**Comment by HazeyOneKenobi** [comment]
Hi, not sure where you are all up to in dev of this, but the blockfrost ipfs gateway doesn't get the request limiting issue anon real describes above (wherein the image displays sometimes and not others) the link path is -

https://ipfs.blockfrost.dev/ipfs/

Lots of NFT's are using this link instead of the usual ipfs gateway, but I'm not sure if it'll be available perpetually.

**Comment by arobsn** [comment]
> Couldn't someone take the API key and then [delete](https://ipfs-shipyard.github.io/nft.storage/client/classes/NFTStorage.html#delete) the CID (allowing it to fall out of IPFS eventually)? It seems like you might need a backend service that holds the API key and actually interacts with nft.storage.

That's true, any can unpin files through this API key.  So is there a recommended place where I can write this endpoint?

**Edit**: I'm going to create this service and put it in a repository here on github. Sorry for the silly questions, I'm new to this open source stuff.

**Comment by arobsn** [comment]
> Hi, not sure where you are all up to in dev of this, but the blockfrost ipfs gateway doesn't get the request limiting issue anon real describes above (wherein the image displays sometimes and not others) the link path is -
> 
> https://ipfs.blockfrost.dev/ipfs/
> 
> Lots of NFT's are using this link instead of the usual ipfs gateway, but I'm not sure if it'll be available perpetually.

Actually the NFTs will be minted with the native IPFS url (like ipfl://... ) and the [auction house will chose the gateway](https://github.com/anon-real/ErgoAuctionHouse/pull/29), so as discoursed above, this way we aren't tied to any gateway.

**Comment by arobsn** [comment]
### New commit
 - replaced direct nft.storage upload by [ErgoUtilsUploadService](https://github.com/anon-br/ErgoUtilsUploadService) in order to keep ApiKey safe.

**Comment by anon-real** [comment]
@anon-br That's great! I am planning to have a backed for the auction house to make things faster (like caching the auctions and low-resolution artworks for faster loading). Maybe later [this](https://github.com/anon-br/ErgoUtilsUploadService) can be included in that backed but for now, it is ok.
So are we good to go?

**Comment by arobsn** [comment]
> That's great! I am planning to have a backed for the auction house to make things faster (like caching the auctions and low-resolution artworks for faster loading). Maybe later [this](https://github.com/anon-br/ErgoUtilsUploadService) can be included in that backed but for now, it is ok.
> So are we good to go?

I'm glad you enjoy it! And sure, we can work on this as soon as you wish, I'm the backend guy!
Also, did you saw [this PR](https://github.com/anon-real/ErgoAuctionHouse/pull/29) on auction house?

**Comment by arobsn** [comment]
> So are we good to go?

@anon-real yes, I think so. The service is running at [https://ergoutilsupload.azurewebsites.net](https://ergoutilsupload.azurewebsites.net/version) and ready for testing.

**Comment by anon-real** [comment]
@anon-br when I issue artwork using IPFS and auction it, it takes like 10 mins before it is possible to load the image. Is it normal?
Other than that, it seems fine. Can you please also add the same functionality for the audio part?

**Comment by anon-real** [comment]
Nvm, added!

**Comment by anon-real** [comment]
@anon-br please contact me on Discord to receive the bounty. @bdkent @catalyst244 please also contact me on Discord to receive some donations. Thanks, guys.

**Comment by bdkent** [comment]
> @anon-br when I issue artwork using IPFS and auction it, it takes like 10 mins before it is possible to load the image. Is it normal?
> 

It's a little hacky, but after uploading to nft.storage, you could hit cloudflare with the CID (fire and forget style) to start priming their cache to cut down on the perceived wait time.

**Comment by anon-real** [comment]
@bdkent that's a good idea. @anon-br can you please hit the URL after upload? either on the server-side or js.

**Comment by arobsn** [comment]
> Can you please also add the same functionality for the audio part?

Yep! I can do this early this week.

> @bdkent that's a good idea. @anon-br can you please hit the URL after upload? either on the server-side or js.

Sure, will do this on server-side.

**Pull request merged**
